### ISSUE TITLE
Atualizar banners de pagamento

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-wirecard#18]
Inserir ícones correspondentes aos métodos, acredito que também seja bom reduzir um pouco o tamanho do logo da wirecard e o ícone do pci (no caso de cartão).

Atualmente está repetindo o mesmo banner:

![Screenshot_2019-10-10 Finalizar compra · My Shop](https://user-images.githubusercontent.com/10326572/66578731-ffeb4d80-eb51-11e9-8f32-954c6ee588d2.png)

**Comment by leomp12** [comment]
@vitorrgg 
![Screenshot_2019-10-10 Finalizar compra · My Shop(1)](https://user-images.githubusercontent.com/10326572/66584437-8a847a80-eb5b-11e9-9c5a-8e8d629bff36.png)

pci no débito online não faz sentido, ficou grande demais também, equanto o logo do itaú ficou pequeno demais, o que pra mim também não faz sentido nesse caso

**Comment by leomp12** [comment]
Naturalmente eu preciso limitar a largura dos banners pra ficar responsivo, conforme a coluna, se você faz banners com larguras diferentes, o que tem largura maior é redimencionado e fica com altura menor, fica com menos destaque.

Neste caso o banner do cartão tá ficando bem menor do que o do débito, o que definitivamente é ruim, ou você faz o do débito com imagem bem menor, ou coloca exatamente do mesmo width x height do que o cartão, aí na renderização continua a mesmo tamanho.

**Comment by vitorrgg** [comment]
Melhor? 
![image](https://user-images.githubusercontent.com/35348281/66597490-777ea400-eb75-11e9-9a41-5d6130936f92.png)

**Comment by leomp12** [comment]
Voltou...

![Screenshot_2020-04-03 Finalizar compra · My Shop](https://user-images.githubusercontent.com/10326572/78399000-7bdac580-75ca-11ea-8398-5a81d072ca97.png)

**Comment by talissonf** [comment]
Icone só pra cartão de crédito?

**Comment by leomp12** [comment]
@talissonf uai, tinha ícone pros outros meios tbm, não? Se tiver é melhor, mas se não deixa só no cartão de crédito mesmo.
Só não rola mostrar o do cartão de crédito nas opções de boleto e débito...

**Comment by talissonf** [comment]
Btf, lembro que só tinha pra cartão de credito antigamente. mas se tiver pra outras formas me envia que eu deixo la no default.

**Comment by leomp12** [comment]
@vitorrgg

**Comment by vitorrgg** [comment]
Oi @talissonf creio que no caso do boleto com wirecard podemos deixar como está no Paghiper: 
![image](https://user-images.githubusercontent.com/35348281/78457105-4b546380-767e-11ea-805a-1eafce2d7cc7.png).

E para débito utilizar a seguinte imagem: 
![debitoWire (1)](https://user-images.githubusercontent.com/35348281/78457135-6fb04000-767e-11ea-9936-31c90914afe2.png)

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-wirecard/commit/b3591dafad26fc792ff8f95dd9b833d56319ed40
