### ISSUE TITLE
Error: Render installments

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-wirecard#24]
When i try to create a transaction with credit card, show me just two instalments. 1x and 12x, others 2x, 3x, 4x,.... until 11 doesnt work. See the image:

![Captura de tela de 2020-03-17 14-17-38](https://user-images.githubusercontent.com/35343551/76882975-2e382c00-685a-11ea-9d19-543ecf4ef3f7.png)
![Captura de tela de 2020-03-17 14-17-44](https://user-images.githubusercontent.com/35343551/76882977-2f695900-685a-11ea-8425-0ed0c3c232f7.png)

I believe that when i client put quantity of installments into configuration, you pick only that. But if the client put 12 parcels of instalments he needs to appear all of them and not just 12x

**Comment by leomp12** [comment]
@talissonf  o lojista deve poder inserir o valor percentual do juros / mês (por parcela) e o número máximo de parcelas, então você calcula o valor de cada parcela seguindo o cálculo da [Tabela Price](https://pt.wikipedia.org/wiki/Tabela_Price) até chegar no número máximo de parcelas.

No caso do exemplo deveria haver opções de parcelamento até 12x, não só à vista e 12x, fica complicado pro lojista ter que calcular o juros e inserir cada opção de parcelamento uma a uma.

**Comment by leomp12** [comment]
Você até pode permitir, opcionalmente, que o lojista insira as opções de parcelamento uma a uma, pode ser interessante pra casos específicos, mas o caso mais comum é o lojista inserir o juros mensal e o número máximo de parcela apenas.

**Comment by talissonf** [comment]
@leomp12  Acho que ja tínhamos conversado sobre isso quando eu tava desenvolvendo o app, você pediu que a opções fossem configuráveis mas que deixasse um default caso não fosse. As opções são configuráveis, porém, o form do admin-marketplace não renderiza a opção de installments amigavelmente limitando a apenas um numero de parcela, sendo que é um array . https://github.com/ecomplus/app-wirecard/blob/master/assets/app.json#L65
Caso não seja configurada a opção de cartão de credito no app, os valores defaults de parcelamento são usados. 
https://github.com/ecomplus/app-wirecard/blob/master/lib/payment-default.js#L11

**Comment by leomp12** [comment]
@talissonf certo, existe um fix a ser feito no admin então, e de fato deve haver uma opção de parcelamento padrão pro caso das opções não serem configuradas.

Mas de qualquer forma o que estamos falando aqui é que o lojista não deve ser obrigado a calcular o juros de todas as parcelas uma a uma, sacou?
A configuração mais simples e mais comum é solicitando apenas o número máximo de parcelas e o juros mensal, com isto você calcula o juros de cada parcela com a tabela price.

Se não houver configuração nenhuma você usa o padrão sim, e opcionalmente você também pode aceitar um vetor de parcelas com o juros de uma a uma, ainda assim o lojista também deve conseguir configurar da forma que mencionamos aqui.

**Comment by leomp12** [comment]
@talissonf o lojista voltou a mencionar isto aqui https://community.e-com.plus/t/wirecard-configuracoes/204 , pode adiantar isto pra nós por favor?

**Comment by talissonf** [comment]
Ok

**Comment by talissonf** [comment]
@leomp12 Fiz um release pra corrigir alguns erros que aconteciam com a renderização das configurações do aplicativo no admin, e também a implementação do cálculo das parcelas utilizando o tabela price. Eu atualizei o aplicativo em todas as lojas que ele foi instalado, pro lojista não ter que remover o aplicativo instalado e instalar novamente pra poder utilizar as configurações atualizadas do admin_settings.
Com esse release, esses dois tópicos https://community.e-com.plus/t/opcoes-de-pagamento/159/2, https://community.e-com.plus/t/wirecard-configuracoes/204/2, foram resolvidos.

**Comment by leomp12** [comment]
Boa @talissonf , valeu !

**Comment by leomp12** [comment]
@matheusgnreis
