### ISSUE TITLE
Pedido desatualizado quando automaticamente autorizado

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-wirecard#27]
Como exemplo o pedido 362499 da loja 1024 já entrou como pago no Wirecard, na plataforma entretando foi salvo como em análise e permaneceu desta forma.

**Comment by leomp12** [comment]
Filho seu @talissonf haha
Tenho uns prints se quiser e te mando em outro local.

**Comment by talissonf** [comment]
@leomp12 pode ser.

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-wirecard/commit/01844b9f0bef8dc3037c2c53911219b71518da0c
