### ISSUE TITLE
Admin settings desatualizado e campo não funcional

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-wirecard#29]
O admin settings publicado aqui não corresponde ao que é instalado atualmente (publicado no Market), nele temos um campo `list_payments` (label _Ordem de Pagamento_) que parece não estar funcionando, inclusive não encontrei no código lugar onde ele é tratado.

- [ ] A task principal é tratar esse campo `list_payments` e atualizar o `application.json` publicado no repo.

Adicionalmente:

- [x] O campo _Nome da loja_ parece estar mal descrito, acredito que isso seja para a fatura do cartão, nesse caso a descrição do campo deveria ser algo como _Nome da loja exibido na fatura do cartão_;
- [x] O campo com label _ Titulo de desconto_ (faltou um acento no _í_) deveria estar dentro do _Desconto_ para organizar melhor, ficou meio confuso o collapse geral da configuração desse app.

**Comment by talissonf** [comment]
https://market.e-com.plus/v2/applications/1238

**Comment by leomp12** [comment]
Hmm, mas na verdade a intenção não é remover o campo do admin settings, mas sim tratá-lo devidamente na reposta para o módulo `list_payments`.
O lojista tentou usá-lo e não fez efeito, removê-lo do admin settings não resolve o problema do lojista.

> No mínimo responda primeiro com cartão de crédito, em geral é a primeira opção de pagamento e é o que o lojista está tentando configurar.

**Comment by talissonf** [comment]
aquele campo foi sobrescrito, ele nao serve de nada la

**Comment by leomp12** [comment]
Tô ligado que ele não serve :smile: 
Mas o negócio é que ainda precisamos de um campo para ordenar as formas de pagamento (o nome da propriedade faz...), vi que tem um `sort` mas este está funcional? Também não achei nada no código tratando ele.

**Comment by talissonf** [comment]
# *https://github.com/ecomplus/app-wirecard/commit/82a4912ac5be327e22c68fa2fc59d3bc1a28a596*

**Comment by leomp12** [comment]
@talissonf você testou?
Seu enum no admin settings indica `'Cartão de Crédito'` e no código você seta `'Cartão de crédito'`, no [sort](https://github.com/ecomplus/app-wirecard/blob/82a4912ac5be327e22c68fa2fc59d3bc1a28a596/routes/ecom/modules/list-payments.js#L174) você não normaliza o case da string então acho que não vai funcionar.

**Comment by talissonf** [comment]
testei sim

**Comment by leomp12** [comment]
Hmm até funciona mas porque na verdade o cartão (último no array por padrão) fica em primeiro mesmo se `config.sort` for `'abc'` ou qualquer outra coisa diferente de `'Boleto Bancário'` e `'Débito Online'`.

```js
'Cartão de Crédito'.indexOf('Cartão de crédito') = -1
```

Selecionando a opção _Cartão de Crédito_ sua função no sort retorna 1 em todos os testes porque `config.sort.indexOf(a.payment_method.name)` dá -1 pras 3 formas de pagamento, nesse caso o último item do array vira primeiro...
