### ISSUE TITLE
Juros não sendo aplicado após a escolha no checkout

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-wirecard#30]
https://app.e-com.plus/#/resources/orders/604a1ce6a735d032cbb8b60b loja 1225, o que está gerando problema, pois cliente está estornando pedido.
Esse é um de teste.

**Comment by matheusgnreis** [comment]
Procedimento foi escolher 3 vezes com juros, cada parcela estava em 55,85, no final ficou 50,70 cada parcela

**Comment by matheusgnreis** [comment]
@leomp12 aparentemente isso ocorre, quando é juros misto. Por exemplo até 2x sem juros e o resto com juros. Para o mesmo pedido, fiz a mesma coisa, mas colocando juros misto e funcionou

**Comment by leomp12** [comment]
Não sei se isso é um erro do app, assim como PagSeguro, Mercadopago e afins, não setamos o valor da parcela no Wirecard, a configuração no aplicativo é só para exibir as opções de parcelamento na vitrine e carrinho, no checkout só enviamos o número de parcelas para o Wirecard na criação da transação, o próprio Wirecard faz o cálculo do valor da parcela conforme a conta e configurações do lojista, não temos como forçar o valor da parcela.

**Comment by leomp12** [comment]
Ou seja, não adianta nada a configuração do app se na conta do Wiercard o cálculo da parcela for diferente, o lojista tem que se certificar que a configuração do app está igual ao que é aplicado na conta dele lá.
Em geral intermediadores não permitem que a gente defina o valor da parcela, isso só é possível em gateway ou adquirente direto, só Pagar.me, Vindi etc.

**Comment by leomp12** [comment]
Se no carrinho o parcelamento está conforme a configuração do lojista, o app está funcionando normalmente, não temos nada a corrigir e esse issue pode ser fechado, nesse caso se o valor aplicado é diferente do que ele quer ele tem que verificar no próprio Wirecard, se é que isso é configurável lá, se não for ele tem que corrigir as configurações do app na E-Com pra replicar o que o Wirecard aplica.
