### ISSUE TITLE
Atualização em pagamento estornado

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-wirecard#31]
Seguinte pedido não foi atualizado automaticamente para estornado:

```
1024
ID 60f6cf62cfb89c2ad56f685c
Wirecard: PAY-5OO1JA2XYPXI
```

> Status estornado está sendo recebido e tratado corretamente?

**Comment by leomp12** [comment]
Até surgiu o problema com outros status também, intermitentemente, então talvez o ideal seja adicionarmos um interval pra buscar os status ativamente no Wirecard (como acredito que esteja sendo feito no app do PagSeguro), como um double check adicional às notificações de status deles.

**Comment by talissonf** [comment]
Blz

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-wirecard/releases/tag/v2.2.0

**Comment by talissonf** [comment]
@leomp12 implementei la

**Comment by leomp12** [comment]
Valeu @talissonf !
Dei um outro release de uma vez revertendo os paliativos pra evitar seguir rodando com 500 pedidos toda hora https://github.com/ecomplus/app-wirecard/commit/4e7c45c06af076c39e5a846391a7463838713f14
Se eu tiver esquecido algo manda bala aí por favor...
