### ISSUE TITLE
Falha ao Autenticar 

### ISSUE THREAD

**Issue by mateusvtoledo** [ecomplus/app-wirecard#33]
Após a Autenticação do APP ele dá o seguinte erro:

![image](https://user-images.githubusercontent.com/92322503/200068938-fc600003-44ef-4b9a-a9b2-daba77dccf69.png)

**Comment by leomp12** [comment]
https://github.com/ecomplus/app-wirecard/commit/cbe9d0327a0944ac67fb745db97b4cd9d8ca18b0
